//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeFree.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmokeFree.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        internal static string AppSetingApplicationColorLabel {
            get {
                return ResourceManager.GetString("AppSetingApplicationColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string AppSetingApplicationContactSection {
            get {
                return ResourceManager.GetString("AppSetingApplicationContactSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Report to Dev Team.
        /// </summary>
        internal static string AppSetingApplicationFeedbackLabel {
            get {
                return ResourceManager.GetString("AppSetingApplicationFeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string AppSetingApplicationNotificationLabel {
            get {
                return ResourceManager.GetString("AppSetingApplicationNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Application.
        /// </summary>
        internal static string AppSetingApplicationRankLabel {
            get {
                return ResourceManager.GetString("AppSetingApplicationRankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Application.
        /// </summary>
        internal static string AppSetingApplicationRestartLabel {
            get {
                return ResourceManager.GetString("AppSetingApplicationRestartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string AppSetingApplicationSection {
            get {
                return ResourceManager.GetString("AppSetingApplicationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Web Site.
        /// </summary>
        internal static string AppSetingApplicationWebSiteLabel {
            get {
                return ResourceManager.GetString("AppSetingApplicationWebSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string AppSetingTutorialSection {
            get {
                return ResourceManager.GetString("AppSetingTutorialSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tutorial.
        /// </summary>
        internal static string AppSetingTutorialTitle {
            get {
                return ResourceManager.GetString("AppSetingTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Color Sheme.
        /// </summary>
        internal static string AppSettingsViewColorPickerTitle {
            get {
                return ResourceManager.GetString("AppSettingsViewColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language.
        /// </summary>
        internal static string AppSettingsViewLanguagePickerTitle {
            get {
                return ResourceManager.GetString("AppSettingsViewLanguagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string AppSettingsViewTitle {
            get {
                return ResourceManager.GetString("AppSettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian ( Bulgaria ).
        /// </summary>
        internal static string BulgarianLanguageDisplayLabel {
            get {
                return ResourceManager.GetString("BulgarianLanguageDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ButtonOkText {
            get {
                return ResourceManager.GetString("ButtonOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open Application web site.
        /// </summary>
        internal static string CantOpenAppWebSiteToastMessage {
            get {
                return ResourceManager.GetString("CantOpenAppWebSiteToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to send message.
        /// </summary>
        internal static string CantSendEmailTitle {
            get {
                return ResourceManager.GetString("CantSendEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accures! Unable to send your issue to application delopment team. Please restart your device or send as a message from other device..
        /// </summary>
        internal static string CantSendIssueEmailMessage {
            get {
                return ResourceManager.GetString("CantSendIssueEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Smoke Test is going to continue for {0}. Are you sure about that?.
        /// </summary>
        internal static string ConfirmStartTestingDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmStartTestingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your Test.
        /// </summary>
        internal static string ConfirmStartTestingDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmStartTestingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your initial selection for Challenge Goal time is less then the current date, please select again.
        /// </summary>
        internal static string CreateChallengeViewModelNewGoalDialogMessage {
            get {
                return ResourceManager.GetString("CreateChallengeViewModelNewGoalDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new Challenge Final Date.
        /// </summary>
        internal static string CreateChallengeViewModelNewGoalDialogTitle {
            get {
                return ResourceManager.GetString("CreateChallengeViewModelNewGoalDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Challenge.
        /// </summary>
        internal static string CreateChallengeViewTitle {
            get {
                return ResourceManager.GetString("CreateChallengeViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final goal date must be greater than current date with {0} days!.
        /// </summary>
        internal static string CreateTestInvalidGoalTimeMessage {
            get {
                return ResourceManager.GetString("CreateTestInvalidGoalTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your self more time!.
        /// </summary>
        internal static string CreateTestInvalidGoalTimeTitle {
            get {
                return ResourceManager.GetString("CreateTestInvalidGoalTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Test.
        /// </summary>
        internal static string CreateTestViewTestStartTestButton {
            get {
                return ResourceManager.GetString("CreateTestViewTestStartTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Test Time Duration.
        /// </summary>
        internal static string CreateTestViewTestTimePicker {
            get {
                return ResourceManager.GetString("CreateTestViewTestTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Test.
        /// </summary>
        internal static string CreateTestViewTiitle {
            get {
                return ResourceManager.GetString("CreateTestViewTiitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s First Set Your Stop Smoking Goal Completition Date!.
        /// </summary>
        internal static string CreateTestViewViewDescriptionLabel {
            get {
                return ResourceManager.GetString("CreateTestViewViewDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string CreateTestViewViewDescriptionLabelButton {
            get {
                return ResourceManager.GetString("CreateTestViewViewDescriptionLabelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception accuress in application. Please contact application develers.
        /// </summary>
        internal static string CriticalApplicationFail {
            get {
                return ResourceManager.GetString("CriticalApplicationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email send successfully.
        /// </summary>
        internal static string EmailSuccesTitle {
            get {
                return ResourceManager.GetString("EmailSuccesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English ( United States ).
        /// </summary>
        internal static string EnglishLanguageDisplayLabel {
            get {
                return ResourceManager.GetString("EnglishLanguageDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error accures! Please restart the application or contact with app development team..
        /// </summary>
        internal static string InternalErrorUserMessage {
            get {
                return ResourceManager.GetString("InternalErrorUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your issue email is send to our development team.Thank you for sending it. We are going to response quick li as we can..
        /// </summary>
        internal static string IssueEmailSuccessMessage {
            get {
                return ResourceManager.GetString("IssueEmailSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no data to send.
        /// </summary>
        internal static string IssueNoDataToSendMessage {
            get {
                return ResourceManager.GetString("IssueNoDataToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to send.
        /// </summary>
        internal static string IssueNoDataToSendTitle {
            get {
                return ResourceManager.GetString("IssueNoDataToSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is not connected to internet network. Please connet to send issue!.
        /// </summary>
        internal static string IssueNoWebConnectionMessage {
            get {
                return ResourceManager.GetString("IssueNoWebConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string IssueNoWebConnectionMessageTitle {
            get {
                return ResourceManager.GetString("IssueNoWebConnectionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string OnBoardingItemButton1 {
            get {
                return ResourceManager.GetString("OnBoardingItemButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string OnBoardingItemButton2 {
            get {
                return ResourceManager.GetString("OnBoardingItemButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string OnBoardingItemButton3 {
            get {
                return ResourceManager.GetString("OnBoardingItemButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReSchedule.png.
        /// </summary>
        internal static string OnBoardingItemImage1 {
            get {
                return ResourceManager.GetString("OnBoardingItemImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.png.
        /// </summary>
        internal static string OnBoardingItemImage2 {
            get {
                return ResourceManager.GetString("OnBoardingItemImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewMode.png.
        /// </summary>
        internal static string OnBoardingItemImage3 {
            get {
                return ResourceManager.GetString("OnBoardingItemImage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Two for current on boarding menu, it may be long, but, may be short..
        /// </summary>
        internal static string OnBoardingItemText1 {
            get {
                return ResourceManager.GetString("OnBoardingItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Two for current on boarding menu, it may be long, but, may be short..
        /// </summary>
        internal static string OnBoardingItemText2 {
            get {
                return ResourceManager.GetString("OnBoardingItemText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Two for current on boarding menu, it may be long, but, may be short..
        /// </summary>
        internal static string OnBoardingItemText3 {
            get {
                return ResourceManager.GetString("OnBoardingItemText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide One.
        /// </summary>
        internal static string OnBoardingItemTitle1 {
            get {
                return ResourceManager.GetString("OnBoardingItemTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Two.
        /// </summary>
        internal static string OnBoardingItemTitle2 {
            get {
                return ResourceManager.GetString("OnBoardingItemTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Three.
        /// </summary>
        internal static string OnBoardingItemTitle3 {
            get {
                return ResourceManager.GetString("OnBoardingItemTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string OnBoardingViewTitle {
            get {
                return ResourceManager.GetString("OnBoardingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string PluralDay {
            get {
                return ResourceManager.GetString("PluralDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string SingleDay {
            get {
                return ResourceManager.GetString("SingleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        internal static string SomethingWentWrongViewModelHeader {
            get {
                return ResourceManager.GetString("SomethingWentWrongViewModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SomethingWentWrong.png.
        /// </summary>
        internal static string SomethingWentWrongViewModelImage {
            get {
                return ResourceManager.GetString("SomethingWentWrongViewModelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report to Developers.
        /// </summary>
        internal static string SomethingWentWrongViewModelReportIssueButtonText {
            get {
                return ResourceManager.GetString("SomethingWentWrongViewModelReportIssueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        internal static string SomethingWentWrongViewModelTitle {
            get {
                return ResourceManager.GetString("SomethingWentWrongViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string SomethingWentWrongViewModelTryAgainButtonText {
            get {
                return ResourceManager.GetString("SomethingWentWrongViewModelTryAgainButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Data Saved.
        /// </summary>
        internal static string TestDataAccuired {
            get {
                return ResourceManager.GetString("TestDataAccuired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage Clean Oxygen Time.
        /// </summary>
        internal static string TestResultAvarageCleanOxygenTimeLabel {
            get {
                return ResourceManager.GetString("TestResultAvarageCleanOxygenTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage For Day.
        /// </summary>
        internal static string TestResultAvarageForDayLabel {
            get {
                return ResourceManager.GetString("TestResultAvarageForDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage Smoke Distance.
        /// </summary>
        internal static string TestResultAvarageSmokeDistance {
            get {
                return ResourceManager.GetString("TestResultAvarageSmokeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Challenge.
        /// </summary>
        internal static string TestResultCreateChallengeButton {
            get {
                return ResourceManager.GetString("TestResultCreateChallengeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test End Date.
        /// </summary>
        internal static string TestResultEndDateLabel {
            get {
                return ResourceManager.GetString("TestResultEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoked Cigars.
        /// </summary>
        internal static string TestResultSmokedCigarsLabel {
            get {
                return ResourceManager.GetString("TestResultSmokedCigarsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Start Date.
        /// </summary>
        internal static string TestResultStartedDateLabel {
            get {
                return ResourceManager.GetString("TestResultStartedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Time.
        /// </summary>
        internal static string TestResultTestTimeLabel {
            get {
                return ResourceManager.GetString("TestResultTestTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Smoke Gaz Time.
        /// </summary>
        internal static string TestResultTotalSmokedGazTime {
            get {
                return ResourceManager.GetString("TestResultTotalSmokedGazTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        internal static string TestResultViewModelTiitle {
            get {
                return ResourceManager.GetString("TestResultViewModelTiitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time when you smoke click the Smoke Button, when you complete your smoke clicke Smoke Done button. It&apos;s very importent to do this. The Test data is going to be used to create your unique challeng, that is going to help you get rid of smoking habbit..
        /// </summary>
        internal static string UnderTestViewDescriptionLabel {
            get {
                return ResourceManager.GetString("UnderTestViewDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string UnderTestViewDescriptionLabelButton {
            get {
                return ResourceManager.GetString("UnderTestViewDescriptionLabelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Time.
        /// </summary>
        internal static string UnderTestViewLastTimeLabel {
            get {
                return ResourceManager.GetString("UnderTestViewLastTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark One Smoked.
        /// </summary>
        internal static string UnderTestViewMarkOneSmokedButton {
            get {
                return ResourceManager.GetString("UnderTestViewMarkOneSmokedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Challenge!.
        /// </summary>
        internal static string UnderTestViewModelCompleteTestButton {
            get {
                return ResourceManager.GetString("UnderTestViewModelCompleteTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Completed.
        /// </summary>
        internal static string UnderTestViewModelCompleteTestMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelCompleteTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Challenge!.
        /// </summary>
        internal static string UnderTestViewModelCompleteTestNotificationMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelCompleteTestNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratuations!.
        /// </summary>
        internal static string UnderTestViewModelCompleteTestTitle {
            get {
                return ResourceManager.GetString("UnderTestViewModelCompleteTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing time is over but no data was collected. You nead to mark smoked cigars in order to collect test data. Please redo the test..
        /// </summary>
        internal static string UnderTestViewModelCreateTestResultErrorMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelCreateTestResultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to collect data.
        /// </summary>
        internal static string UnderTestViewModelCreateTestResultErrorTitle {
            get {
                return ResourceManager.GetString("UnderTestViewModelCreateTestResultErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 10min. delay your previos smoke was marked as done..
        /// </summary>
        internal static string UnderTestViewModelMarkAfterDelayDialogMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelMarkAfterDelayDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your smoke is mark as finished.
        /// </summary>
        internal static string UnderTestViewModelOneSmokeTreshHoldNotificationMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelOneSmokeTreshHoldNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Smoke is mark done.
        /// </summary>
        internal static string UnderTestViewModelOneSmokeTreshHoldNotificationTitle {
            get {
                return ResourceManager.GetString("UnderTestViewModelOneSmokeTreshHoldNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Testing.
        /// </summary>
        internal static string UnderTestViewModelRestartTestingLabel {
            get {
                return ResourceManager.GetString("UnderTestViewModelRestartTestingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you smoking now?.
        /// </summary>
        internal static string UnderTestViewModelStartSmokeConfirmMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelStartSmokeConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Test.
        /// </summary>
        internal static string UnderTestViewModelStartSmokeConfirmTitle {
            get {
                return ResourceManager.GetString("UnderTestViewModelStartSmokeConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Ok if you are done with smoking.
        /// </summary>
        internal static string UnderTestViewModelStopSmokeConfirmMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelStopSmokeConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you done with smoke?.
        /// </summary>
        internal static string UnderTestViewModelStopSmokeConfirmTitle {
            get {
                return ResourceManager.GetString("UnderTestViewModelStopSmokeConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting the test is going to erase all collected data. Are you shore?.
        /// </summary>
        internal static string UnderTestViewModelStopTestMessage {
            get {
                return ResourceManager.GetString("UnderTestViewModelStopTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Sence.
        /// </summary>
        internal static string UnderTestViewSmokeSenceLabel {
            get {
                return ResourceManager.GetString("UnderTestViewSmokeSenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoked.
        /// </summary>
        internal static string UnderTestViewSmokingLabel {
            get {
                return ResourceManager.GetString("UnderTestViewSmokingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Smoking.
        /// </summary>
        internal static string UnderTestViewStartSmokingButton {
            get {
                return ResourceManager.GetString("UnderTestViewStartSmokingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Left Time.
        /// </summary>
        internal static string UnderTestViewTestLeftTimeLabel {
            get {
                return ResourceManager.GetString("UnderTestViewTestLeftTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Test.
        /// </summary>
        internal static string UnderTestViewTiitle {
            get {
                return ResourceManager.GetString("UnderTestViewTiitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addicted.
        /// </summary>
        internal static string UserSmokeStatusSetBad {
            get {
                return ResourceManager.GetString("UserSmokeStatusSetBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuck.
        /// </summary>
        internal static string UserSmokeStatusSetConcern {
            get {
                return ResourceManager.GetString("UserSmokeStatusSetConcern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concern.
        /// </summary>
        internal static string UserSmokeStatusSetQuiter {
            get {
                return ResourceManager.GetString("UserSmokeStatusSetQuiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trobles.
        /// </summary>
        internal static string UserSmokeStatusSetSmoker {
            get {
                return ResourceManager.GetString("UserSmokeStatusSetSmoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Now.
        /// </summary>
        internal static string UserSmokeStatusSetWorst {
            get {
                return ResourceManager.GetString("UserSmokeStatusSetWorst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string UserSmokeStatusTitle {
            get {
                return ResourceManager.GetString("UserSmokeStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
    }
}
