//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeFree.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmokeFree.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не.
        /// </summary>
        internal static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string ButtonOkText {
            get {
                return ResourceManager.GetString("ButtonOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоят тест ще продължи {0}. Сигурен ли си, че това ще бъде достатъчно?.
        /// </summary>
        internal static string ConfirmStartTestingDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmStartTestingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Започни своя тест..
        /// </summary>
        internal static string ConfirmStartTestingDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmStartTestingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайната дата за успешно спиране на цигарите трябва да е по голяма от днешната със {0} дни!.
        /// </summary>
        internal static string CreateTestInvalidGoalTimeMessage {
            get {
                return ResourceManager.GetString("CreateTestInvalidGoalTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно е повече време!.
        /// </summary>
        internal static string CreateTestInvalidGoalTimeTitle {
            get {
                return ResourceManager.GetString("CreateTestInvalidGoalTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Започни своя тест.
        /// </summary>
        internal static string CreateTestViewTestStartTestButton {
            get {
                return ResourceManager.GetString("CreateTestViewTestStartTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избере времеви диапазон за тестване.
        /// </summary>
        internal static string CreateTestViewTestTimePicker {
            get {
                return ResourceManager.GetString("CreateTestViewTestTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на Тест.
        /// </summary>
        internal static string CreateTestViewTiitle {
            get {
                return ResourceManager.GetString("CreateTestViewTiitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери своята цел! До коя дата искаш да спреш този навик?.
        /// </summary>
        internal static string CreateTestViewViewDescriptionLabel {
            get {
                return ResourceManager.GetString("CreateTestViewViewDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължи.
        /// </summary>
        internal static string CreateTestViewViewDescriptionLabelButton {
            get {
                return ResourceManager.GetString("CreateTestViewViewDescriptionLabelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна неочаквана грешка. Рестартирайте приложението или се свържете със създателите..
        /// </summary>
        internal static string InternalErrorUserMessage {
            get {
                return ResourceManager.GetString("InternalErrorUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължи.
        /// </summary>
        internal static string OnBoardingItemButton1 {
            get {
                return ResourceManager.GetString("OnBoardingItemButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължи.
        /// </summary>
        internal static string OnBoardingItemButton2 {
            get {
                return ResourceManager.GetString("OnBoardingItemButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string OnBoardingItemButton3 {
            get {
                return ResourceManager.GetString("OnBoardingItemButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReSchedule.png.
        /// </summary>
        internal static string OnBoardingItemImage1 {
            get {
                return ResourceManager.GetString("OnBoardingItemImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.png.
        /// </summary>
        internal static string OnBoardingItemImage2 {
            get {
                return ResourceManager.GetString("OnBoardingItemImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewMode.png.
        /// </summary>
        internal static string OnBoardingItemImage3 {
            get {
                return ResourceManager.GetString("OnBoardingItemImage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едно много дълго обяснение, какво се случва тук!.
        /// </summary>
        internal static string OnBoardingItemText1 {
            get {
                return ResourceManager.GetString("OnBoardingItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едно много дълго обяснение, какво се случва тук!.
        /// </summary>
        internal static string OnBoardingItemText2 {
            get {
                return ResourceManager.GetString("OnBoardingItemText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едно много дълго обяснение, какво се случва тук!.
        /// </summary>
        internal static string OnBoardingItemText3 {
            get {
                return ResourceManager.GetString("OnBoardingItemText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насока Едно.
        /// </summary>
        internal static string OnBoardingItemTitle1 {
            get {
                return ResourceManager.GetString("OnBoardingItemTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насока Две.
        /// </summary>
        internal static string OnBoardingItemTitle2 {
            get {
                return ResourceManager.GetString("OnBoardingItemTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насока Три.
        /// </summary>
        internal static string OnBoardingItemTitle3 {
            get {
                return ResourceManager.GetString("OnBoardingItemTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ръководство.
        /// </summary>
        internal static string OnBoardingViewTitle {
            get {
                return ResourceManager.GetString("OnBoardingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дни.
        /// </summary>
        internal static string PluralDay {
            get {
                return ResourceManager.GetString("PluralDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ден.
        /// </summary>
        internal static string SingleDay {
            get {
                return ResourceManager.GetString("SingleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        internal static string UnderTestViewTiitle {
            get {
                return ResourceManager.GetString("UnderTestViewTiitle", resourceCulture);
            }
        }
    }
}
